In [70]:
import numpy as np
import pandas as pd

In [71]:
df = pd.read_csv("Tasks2.csv")

In [72]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []

for i in range(len(X)):
  task = re.sub('[^a-zA-Z]', ' ', df.iloc[i, 4])
  task = task.lower()
  task = task.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  task = [ps.stem(word) for word in task if word not in all_stopwords]
  task = ' '.join(task)
  corpus.append(task)

print(corpus)

['math homework', 'read assign', 'lunch break', 'scienc project research', 'soccer practic', 'dinner famili', 'english essay', 'prepar tomorrow present', 'morn jog', 'histori quiz prepar', 'lunch break', 'group project meet', 'piano practic', 'physic homework', 'relax unwind', 'chemistri lab report', 'histori lectur note', 'art class', 'meet tutor', 'gym workout', 'dinner', 'french homework', 'math test prepar', 'scienc experi', 'lunch break', 'chemistri revis', 'swim practic', 'volunt work', 'music practic', 'read', 'math homework', 'scienc project', 'lunch', 'histori essay', 'gym session', 'debat practic', 'dinner friend', 'read', 'physic revis', 'chemistri lab', 'lunch', 'art project', 'basketbal practic', 'music practic', 'dinner', 'read', 'math quiz prepar', 'scienc lab report', 'lunch', 'gym workout']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [73]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=75)
embed = cv.fit_transform(corpus).toarray()
print(embed)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [74]:
print(df)

    taskid  accountname      current_datetime          due_datetime  \
0        1     StudentA   2024-06-23 08:00:00   2024-06-23 12:00:00   
1        2     StudentA   2024-06-23 09:30:00   2024-06-23 11:30:00   
2        3     StudentA   2024-06-23 12:00:00   2024-06-23 14:00:00   
3        4     StudentA   2024-06-23 14:30:00   2024-06-23 16:00:00   
4        5     StudentA   2024-06-23 16:30:00   2024-06-23 18:30:00   
5        6     StudentA   2024-06-23 19:00:00   2024-06-23 21:00:00   
6        7     StudentA   2024-06-23 21:30:00   2024-06-23 23:00:00   
7        8     StudentA   2024-06-23 23:30:00   2024-06-24 01:00:00   
8        9     StudentA   2024-06-24 08:00:00   2024-06-24 10:00:00   
9       10     StudentA   2024-06-24 10:30:00   2024-06-24 13:00:00   
10      11     StudentA   2024-06-24 13:30:00   2024-06-24 15:30:00   
11      12     StudentA   2024-06-24 16:00:00   2024-06-24 18:00:00   
12      13     StudentA   2024-06-24 18:30:00   2024-06-24 20:30:00   
13    

In [75]:
print(df.shape)

(50, 9)


In [76]:
len(df)

50

In [78]:
for i in range(len(df)):
  df[' brief_desc'][i] = embed[i]
print(df)

    taskid  accountname      current_datetime          due_datetime  \
0        1     StudentA   2024-06-23 08:00:00   2024-06-23 12:00:00   
1        2     StudentA   2024-06-23 09:30:00   2024-06-23 11:30:00   
2        3     StudentA   2024-06-23 12:00:00   2024-06-23 14:00:00   
3        4     StudentA   2024-06-23 14:30:00   2024-06-23 16:00:00   
4        5     StudentA   2024-06-23 16:30:00   2024-06-23 18:30:00   
5        6     StudentA   2024-06-23 19:00:00   2024-06-23 21:00:00   
6        7     StudentA   2024-06-23 21:30:00   2024-06-23 23:00:00   
7        8     StudentA   2024-06-23 23:30:00   2024-06-24 01:00:00   
8        9     StudentA   2024-06-24 08:00:00   2024-06-24 10:00:00   
9       10     StudentA   2024-06-24 10:30:00   2024-06-24 13:00:00   
10      11     StudentA   2024-06-24 13:30:00   2024-06-24 15:30:00   
11      12     StudentA   2024-06-24 16:00:00   2024-06-24 18:00:00   
12      13     StudentA   2024-06-24 18:30:00   2024-06-24 20:30:00   
13    

<ipython-input-78-44d580545166>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[' brief_desc'][i] = embed[i]
<ipython-input-78-44d580545166>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[' brief_desc'][i] = embed[i]
<ipython-input-78-44d580545166>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[' brief_desc'][i] = embed[i]
<ipython-input-78-44d580545166>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of

In [79]:
df = pd.concat([df.pop(' brief_desc').apply(pd.Series), df[' task_type'], df[' hours_left'], df[' weight'], df[' completed']], axis=1)

In [80]:
print(df)

    0  1  2  3  4  5  6  7  8  9  ...  44  45  46  47  48  49  \
0   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
1   0  1  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
2   0  0  0  1  0  0  0  0  0  0  ...   0   0   0   0   0   0   
3   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
4   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
5   0  0  0  0  0  0  0  1  0  0  ...   0   0   0   0   0   0   
6   0  0  0  0  0  0  0  0  1  1  ...   0   0   0   0   0   0   
7   0  0  0  0  0  0  0  0  0  0  ...   1   0   0   0   0   0   
8   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
9   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
10  0  0  0  1  0  0  0  0  0  0  ...   0   0   0   0   0   0   
11  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
12  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
13  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
14  0  0  0  0  0  0  0  

In [81]:
X = df.iloc[:,:-2].values
y = df.iloc[:,-2].values

In [82]:
print(X)

[[0 0 0 ... 0 ' Curricular' 4.0]
 [0 1 0 ... 0 ' Curricular' 10.0]
 [0 0 0 ... 0 ' Personal' 2.0]
 ...
 [0 0 0 ... 0 ' Curricular' 2.0]
 [0 0 0 ... 0 ' Personal' 1.5]
 [0 0 0 ... 1 ' Extra-Curricular' 15.0]]


In [83]:
print(y)

[10  7  2  8  4  2  9  6  4  7  2  8  6 10  2 10  6  4  8  4  2  8 10  6
  2  8  4  6  4  2 10  8  2  8  4  6  2  2  8  6  2  6  4  4  2  2 10  8
  2  4]


In [84]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [50])], remainder='passthrough')
# transformer: what kind of transformation and for what columns. remainder: what to do with other columns
X = np.array(ct.fit_transform(X))

In [85]:
X

array([[0.0, 1.0, 0.0, ..., 0, 0, 4.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 10.0],
       [0.0, 0.0, 0.0, ..., 0, 0, 2.0],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 0, 2.0],
       [0.0, 0.0, 0.0, ..., 0, 0, 1.5],
       [0.0, 0.0, 1.0, ..., 0, 1, 15.0]], dtype=object)

In [86]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(n_estimators=10, random_state=0)
rf_reg.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [123]:
def prep(task):
  desc= task[0]
  typ=task[1]
  hrsleft=task[2]
  ps=PorterStemmer()
  all_stopwords = stopwords.words('english')
  ntask = [ps.stem(word) for word in desc if word not in all_stopwords]
  ntask = ' '.join(ntask)
  ncorpus=[ntask]
  n_test=cv.transform(ncorpus).toarray()
  ntest_ = n_test[0]
  prep_ = [i for i in ntest_]
  prep_.append(hrsleft)
  if typ == 'Curricular':
    prep_.insert(0, 0.0)
    prep_.insert(1, 1.0)
    prep_.insert(2, 0.0)
    prep_.insert(3, 0.0)
  elif typ == 'Personal':
    prep_.insert(0, 0.0)
    prep_.insert(1, 0.0)
    prep_.insert(2, 0.0)
    prep_.insert(3, 1.0)
  elif typ == 'Co-Curricular':
    prep_.insert(0, 1.0)
    prep_.insert(1, 0.0)
    prep_.insert(2, 0.0)
    prep_.insert(3, 0.0)
  else:
    prep_.insert(0, 0.0)
    prep_.insert(1, 0.0)
    prep_.insert(2, 1.0)
    prep_.insert(3, 0.0)

  print(prep_)
  return prep_



In [128]:
result = [prep(['maths homework', 'Curricular', 3])]

[0.0, 1.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]


In [129]:
print(result)

[[0.0, 1.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]]


In [130]:
rf_reg.predict(result)

array([8.2])