In [29]:
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv("Tasks.csv")

In [31]:
X = df.iloc[:,5:-1].values
y = df.iloc[:,-1].values

In [32]:
print(X)

[['Co-curricular' 120.4889583]
 ['Academics' 183.5722917]
 ['Academics' 3.572291667]
 ['Co-curricular' 1803.572292]
 ['Extra-curricular' 3.572291667]
 ['Co-curricular' 11.07229167]
 ['Co-curricular' 63.57229167]
 ['Co-curricular' 18.57229167]
 ['Co-curricular' 123.5722917]
 ['Personal' 289.780625]
 ['Personal' 1.072291667]
 ['Extra-curricular' 3.572291667]
 ['Co-curricular' 3.572291667]
 ['Co-curricular' 19.780625]
 ['Academics' 423.5722917]
 ['Academics' 1803.572292]
 ['Personal' 13.57229167]
 ['Co-curricular' 19.780625]
 ['Co-curricular' 19.780625]
 ['Extra-curricular' 843.5722917]]


In [33]:
print(y)

[ 6  7 10  5  5  6  8  8  8  3  6  5  7 10  9 10  4 10 10  5]


In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# transformer: what kind of transformation and for what columns. remainder: what to do with other columns
X = np.array(ct.fit_transform(X))

In [35]:
X

array([[0.0, 1.0, 0.0, 0.0, 120.4889583],
       [1.0, 0.0, 0.0, 0.0, 183.5722917],
       [1.0, 0.0, 0.0, 0.0, 3.572291667],
       [0.0, 1.0, 0.0, 0.0, 1803.572292],
       [0.0, 0.0, 1.0, 0.0, 3.572291667],
       [0.0, 1.0, 0.0, 0.0, 11.07229167],
       [0.0, 1.0, 0.0, 0.0, 63.57229167],
       [0.0, 1.0, 0.0, 0.0, 18.57229167],
       [0.0, 1.0, 0.0, 0.0, 123.5722917],
       [0.0, 0.0, 0.0, 1.0, 289.780625],
       [0.0, 0.0, 0.0, 1.0, 1.072291667],
       [0.0, 0.0, 1.0, 0.0, 3.572291667],
       [0.0, 1.0, 0.0, 0.0, 3.572291667],
       [0.0, 1.0, 0.0, 0.0, 19.780625],
       [1.0, 0.0, 0.0, 0.0, 423.5722917],
       [1.0, 0.0, 0.0, 0.0, 1803.572292],
       [0.0, 0.0, 0.0, 1.0, 13.57229167],
       [0.0, 1.0, 0.0, 0.0, 19.780625],
       [0.0, 1.0, 0.0, 0.0, 19.780625],
       [0.0, 0.0, 1.0, 0.0, 843.5722917]], dtype=object)

In [36]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(degree=4)
X_poly = poly.fit_transform(X)
poly_reg = LinearRegression()
poly_reg.fit(X_poly, y)

LinearRegression()

In [39]:
X_test = poly.transform([[1.0, 0.0, 0.0, 0.0, 3.0]])
poly_reg.predict(X_test)

array([8.51834193])

In [46]:
poly_reg.predict(poly.transform([[1.0, 0.0, 0.0, 0.0, 3000]]))

array([-498576.98221732])

In [47]:
poly_reg.predict(poly.transform([[0.0,1.0,0.0,0.0,3.0]]))

array([5.82311048])

In [48]:
poly_reg.predict(poly.transform([[0.0,1.0,0.0,0.0,1000]]))

array([12456.93400959])

In [41]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(n_estimators=10, random_state=0)
rf_reg.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [42]:
rf_reg.predict([[1.0, 0.0, 0.0, 0.0, 3.0]])

array([8.8])

In [44]:
rf_reg.predict([[1.0, 0.0, 0.0, 0.0, 3000]])

array([8.7])

In [45]:
rf_reg.predict([[0.0,1.0,0.0,0.0,3.0]])

array([7.])

In [43]:
rf_reg.predict([[0.0,1.0,0.0,0.0,1000]])

array([6.3])

In [49]:
rf_reg.predict([[0.0,0.0,1.0,0.0,3.0]])

array([5.5])

In [50]:
rf_reg.predict([[0.0,0.0,1.0,0.0,1000]])

array([5.5])

In [51]:
rf_reg.predict([[0.0,0.0,0.0,1.0,3.0]])

array([5.9])

In [52]:
rf_reg.predict([[0.0,0.0,0.0,1.0,1000]])

array([3.])